name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and provide to QA team
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5

    - name: Setup Java JDK
      uses:  actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Change wrapper permission
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew assembleDebug
    
